

pipeline {
    agent any
    

    stages {
        stage('clean and install') {
            steps {
               bat 'mvn clean -f SpringmvcAssignment5/pom.xml'
            }
        }
        stage('Package') {
            steps {
               bat 'mvn package -f SpringmvcAssignment5/pom.xml'
            }
        }
    }
}
